project_name: irestore
builds:
  - id: darwin-build
    main: ./cmd/irestore
    env:
      - CGO_ENABLED=1
    goos:
      - darwin
  - id: linux-build
    main: ./cmd/irestore
    env:
      - CGO_ENABLED=0
    goos:
      - linux
  - id: windows-build
    main: ./cmd/irestore
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    goos:
      - windows

checksum:
  name_template: 'checksums.txt'
