project_name: irestore
builds:
  - id: darwin-build-amd64
    main: ./main.go
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
  - id: darwin-build-arm64
    main: ./main.go
    env:
      - CGO_ENABLED=1
      - CC=aarch64-apple-darwin21.4-clang
      - CXX=aarch64-apple-darwin21.4-clang++
    goos:
      - darwin
    goarch:
      - arm64
  - id: linux-build
    main: ./cmd/irestore
    env:
      - CGO_ENABLED=1
    goos:
      - linux
  - id: windows-build
    main: ./cmd/irestore
    ldflags: -buildmode=exe
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64

checksum:
  name_template: 'checksums.txt'
