on:
  push:
    tags:
      - "v*.*.*"

jobs:
  goreleaser:
    runs-on: macos-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --force --tags
      - run: brew install mingw-w64
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.1'
          cache: true
      - uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
